### ISSUE TITLE
你好！我显卡5700有个黑屏问题

### ISSUE THREAD

**Issue by zhixiangyao** [erhuoL/hackintosh-B450m-mortar-max#1]
安装的系统是10.15.6
ryzen 1400
b450m 迫击炮
讯景 5700
oc启动install 出现apple logo，
loading完毕后，黑屏😭
大佬你知道啥问题嘛

**Comment by erhuoL** [comment]
更换迫击炮的oc吧，我的是带max的

**Comment by zhixiangyao** [comment]
> 更换迫击炮的oc吧，我的是带max的

嗯嗯 已经解决了
