### ISSUE TITLE
兄弟，你是怎么安装的，是引导恢复镜像恢复安装吗

### ISSUE THREAD

**Issue by simonfire007** [erhuoL/hackintosh-B450m-mortar-max#2]
我的主板和CPU和你的一样，显卡是蓝宝石rx5500xt oc，用你的efi，去掉了一些配置，能引导进恢复镜像，恢复安装的时候提示“未能与恢复服务器联系”，试了10.15.3,10.15.6,10.15.7都是这样子

**Comment by erhuoL** [comment]
直接安装就行

**Comment by erhuoL** [comment]
就常规的制作安装硬盘就行

**Comment by simonfire007** [comment]
我是按这个教程，用的是几百mb的恢复镜像，进去之后再联网恢复。https://dortania.github.io/OpenCore-Install-Guide/installer-guide/
你是用的完整的镜像制作的安装盘吗

**Comment by erhuoL** [comment]
恩，用的完整的镜像制作的安装盘，然后安装的

**Comment by simonfire007** [comment]
好，晚上看看能不能装上

**Comment by simonfire007** [comment]
感谢兄弟的回复，找了个完整的镜像，写到u盘，然后替换efi，成功安装。

**Comment by erhuoL** [comment]
恭喜，如果补丁有问题的就自己去爬帖子解决下吧，另外求star
